language: go
sudo: false
go:
- 1.8
- 1.7.4
install:
- go get -t ./...
- go get github.com/alecthomas/gometalinter
- gometalinter --install
before_script:
- gometalinter --deadline 10m $(go list ./... | grep -v /vendor/ | awk -F\/ '{ print $NF}')
script:
- go build ./... 
