language: go
sudo: false
go:
- 1.8
- 1.7.4
install:
- go get -t ./...
- go get github.com/alecthomas/gometalinter
- gometalinter --install
before_script:
- gometalinter --vendor --deadline 10m --errors ./...
script:
- go build $(go list ./... | grep -v /vendor/) 
after_script:
- if [[ "$TRAVIS_GO_VERSION" == 1.7.* ]]; then ./scripts/cov.sh TRAVIS; fi
