language: go
sudo: false
go:
- 1.8
- 1.7.4
install:
- go get github.com/alecthomas/gometalinter
- gometalinter --install
script:
- go build $(go list ./... | grep -v /vendor/) 
- travis_wait 20 gometalinter ./... --vendor --deadline 20m --errors
after_script:
- if [[ "$TRAVIS_GO_VERSION" == 1.7.* ]]; then ./scripts/cov.sh TRAVIS; fi
